# Generated by Django 4.2.6 on 2023-10-24 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home_interface", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="competition",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussions",
                to="home_interface.competition",
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="category",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Category 1"), (2, "Category 2"), (3, "Category 3")],
                default=1,
            ),
        ),
    ]
