# Generated by Django 4.2.5 on 2023-10-24 00:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home_interface", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="competition",
            old_name="end_date",
            new_name="end_regi",
        ),
        migrations.RenameField(
            model_name="competition",
            old_name="description",
            new_name="intro",
        ),
        migrations.RenameField(
            model_name="competition",
            old_name="start_date",
            new_name="start_regi",
        ),
        migrations.AddField(
            model_name="competition",
            name="category",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Category 1"), (2, "Category 2"), (3, "Category 3")],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="competition_images/"
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="competition",
            name="start_compt",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="competition",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.IntegerField(
                unique=True,
                validators=[
                    django.core.validators.MaxValueValidator(20),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
        migrations.CreateModel(
            name="Discussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("discuss_time", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discussions",
                        to="home_interface.user",
                    ),
                ),
            ],
        ),
    ]
