# Generated by Django 4.2.5 on 2023-10-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_interface", "0002_rename_end_date_competition_end_regi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="start_compt",
            field=models.DateField(),
        ),
    ]
