# Generated by Django 4.2.6 on 2023-10-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_interface", "0002_discussion_competition_alter_competition_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now=True, verbose_name="last login"),
        ),
    ]
