# Generated by Django 4.2.5 on 2023-10-24 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home_interface", "0003_alter_competition_start_compt"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="competition",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussions",
                to="home_interface.competition",
            ),
        ),
    ]
