# Generated by Django 4.2.6 on 2023-10-27 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home_interface", "0003_user_last_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.AddField(
            model_name="team",
            name="intro",
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="user_email",
            field=models.EmailField(default="sjtu@gmail.com", max_length=254),
        ),
        migrations.AddField(
            model_name="user",
            name="user_grade",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Grade 1"),
                    (2, "Grade 2"),
                    (3, "Grade 3"),
                    (4, "Grade 4"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="competition",
            name="category",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Category 1"), (2, "Category 2"), (3, "Category 3")]
            ),
        ),
        migrations.AlterField(
            model_name="discussion",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discussions",
                to="home_interface.competition",
            ),
        ),
        migrations.CreateModel(
            name="TeamApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_applications",
                        to="home_interface.user",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="home_interface.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="home_interface.user",
                    ),
                ),
                (
                    "related_application",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home_interface.teamapplication",
                    ),
                ),
            ],
        ),
    ]
