# Generated by Django 4.2.6 on 2023-10-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "home_interface",
            "0004_remove_user_last_login_team_intro_user_user_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now=True, verbose_name="last login"),
        ),
    ]
