# Generated by Django 4.2.6 on 2023-10-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home_interface", "0005_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_authenticated",
            field=models.BooleanField(default=False),
        ),
    ]
